// const districts = [
//     // { "id": "ariyalur", "name": "Ariyalur" },
//     // { "id": "chengalpattu", "name": "Chengalpattu" },
//     // { "id": "chennai", "name": "Chennai" },
//     // { "id": "coimbatore", "name": "Coimbatore" },
//     // { "id": "cuddalore", "name": "Cuddalore" },
//     // { "id": "dharmapuri", "name": "Dharmapuri" },
//     // { "id": "dindigul", "name": "Dindigul" },
//     // { "id": "erode", "name": "Erode" },
//     // { "id": "kallakurichi", "name": "Kallakurichi" },
//     // { "id": "kancheepuram", "name": "Kancheepuram" },
//     // { "id": "kanniyakumari", "name": "Kanniyakumari" },
//     // { "id": "karur", "name": "Karur" },
//     // { "id": "krishnagiri", "name": "Krishnagiri" },
//     // { "id": "madurai", "name": "Madurai" },
//     // { "id": "mayiladuthurai", "name": "Mayiladuthurai" },
//     // { "id": "nagapattinam", "name": "Nagapattinam" },
//     // { "id": "namakkal", "name": "Namakkal" },
//     // { "id": "perambalur", "name": "Perambalur" },
//     // { "id": "pudukkottai", "name": "Pudukkottai" },
//     // { "id": "ramanathapuram", "name": "Ramanathapuram" },
//     // { "id": "ranipet", "name": "Ranipet" },
//     // { "id": "salem", "name": "Salem" },
//     // { "id": "sivaganga", "name": "Sivaganga" },
//     // { "id": "tenkasi", "name": "Tenkasi" },
//     // { "id": "thanjavur", "name": "Thanjavur" },
//     // { "id": "the_nilgiris", "name": "The Nilgiris" },
//     // { "id": "theni", "name": "Theni" },
//     // { "id": "thiruvallur", "name": "Thiruvallur" },
//     // { "id": "thiruvarur", "name": "Thiruvarur" },
//     // { "id": "thoothukkudi", "name": "Thoothukkudi" },
//     // { "id": "tiruchirappalli", "name": "Tiruchirappalli" },
//     // { "id": "tirunelveli", "name": "Tirunelveli" },
//     // { "id": "tirupathur", "name": "Tirupathur" },
//     // { "id": "tiruppur", "name": "Tiruppur" },
//     // { "id": "tiruvannamalai", "name": "Tiruvannamalai" },
//     // { "id": "vellore", "name": "Vellore" },
//     // { "id": "viluppuram", "name": "Viluppuram" },
//     // { "id": "virudhunagar", "name": "Virudhunagar" }
// ]

// export default districts;